services:
  - type: web
    name: dragon-boat-new
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "sh startup.sh"
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11