services:
  - type: web
    name: dragon-boat-new
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "sh startup.sh"
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: ”3.11.6“